#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Feb 18, 2021 05:08:49 PM CET  platform: Windows NT

"""
I'll replace this script with my own backend
 - vXtreniusX
"""
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk


try:
    import ttk
    py3 = False # Propably unneccesary, since Tuxemon's python 2 support is dropped.
	# I'll try to make some sort of a popup/message, when script is running in this python version.
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global Install_path
    Install_path = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def Start_Install():
    print('Installer_support.Start_Install')
    print(Install_path.get()) # Here installation will begin
    sys.stdout.flush()

def select_path():
    print('Installer_support.select_path') # Basicaly a placeholder for opening file select
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Installer # Import gui, if support module is called first
    Installer.vp_start_gui()
